#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crtvu.Dal
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="teamsmsdb")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Inserttb_branch(tb_branch instance);
    partial void Updatetb_branch(tb_branch instance);
    partial void Deletetb_branch(tb_branch instance);
    partial void Inserttb_content(tb_content instance);
    partial void Updatetb_content(tb_content instance);
    partial void Deletetb_content(tb_content instance);
    partial void Inserttb_content_category(tb_content_category instance);
    partial void Updatetb_content_category(tb_content_category instance);
    partial void Deletetb_content_category(tb_content_category instance);
    partial void Inserttb_course(tb_course instance);
    partial void Updatetb_course(tb_course instance);
    partial void Deletetb_course(tb_course instance);
    partial void Inserttb_datatime(tb_datatime instance);
    partial void Updatetb_datatime(tb_datatime instance);
    partial void Deletetb_datatime(tb_datatime instance);
    partial void Inserttb_faculty(tb_faculty instance);
    partial void Updatetb_faculty(tb_faculty instance);
    partial void Deletetb_faculty(tb_faculty instance);
    partial void Inserttb_sc(tb_sc instance);
    partial void Updatetb_sc(tb_sc instance);
    partial void Deletetb_sc(tb_sc instance);
    partial void Inserttb_student(tb_student instance);
    partial void Updatetb_student(tb_student instance);
    partial void Deletetb_student(tb_student instance);
    partial void Inserttb_teacher(tb_teacher instance);
    partial void Updatetb_teacher(tb_teacher instance);
    partial void Deletetb_teacher(tb_teacher instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Crtvu.Dal.Properties.Settings.Default.teamsmsdbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_branch> tb_branch
		{
			get
			{
				return this.GetTable<tb_branch>();
			}
		}
		
		public System.Data.Linq.Table<tb_content> tb_content
		{
			get
			{
				return this.GetTable<tb_content>();
			}
		}
		
		public System.Data.Linq.Table<tb_content_category> tb_content_category
		{
			get
			{
				return this.GetTable<tb_content_category>();
			}
		}
		
		public System.Data.Linq.Table<tb_course> tb_course
		{
			get
			{
				return this.GetTable<tb_course>();
			}
		}
		
		public System.Data.Linq.Table<tb_datatime> tb_datatime
		{
			get
			{
				return this.GetTable<tb_datatime>();
			}
		}
		
		public System.Data.Linq.Table<tb_faculty> tb_faculty
		{
			get
			{
				return this.GetTable<tb_faculty>();
			}
		}
		
		public System.Data.Linq.Table<tb_sc> tb_sc
		{
			get
			{
				return this.GetTable<tb_sc>();
			}
		}
		
		public System.Data.Linq.Table<tb_student> tb_student
		{
			get
			{
				return this.GetTable<tb_student>();
			}
		}
		
		public System.Data.Linq.Table<tb_teacher> tb_teacher
		{
			get
			{
				return this.GetTable<tb_teacher>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_branch")]
	public partial class tb_branch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _name;
		
		private string _first_char;
		
		private System.Nullable<int> _phone;
		
		private string _email;
		
		private string _password;
		
		private string _otherone;
		
		private string _othertwo;
		
		private EntitySet<tb_faculty> _tb_faculty;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onfirst_charChanging(string value);
    partial void Onfirst_charChanged();
    partial void OnphoneChanging(System.Nullable<int> value);
    partial void OnphoneChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnotheroneChanging(string value);
    partial void OnotheroneChanged();
    partial void OnothertwoChanging(string value);
    partial void OnothertwoChanged();
    #endregion
		
		public tb_branch()
		{
			this._tb_faculty = new EntitySet<tb_faculty>(new Action<tb_faculty>(this.attach_tb_faculty), new Action<tb_faculty>(this.detach_tb_faculty));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(255)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_char", DbType="NVarChar(1)")]
		public string first_char
		{
			get
			{
				return this._first_char;
			}
			set
			{
				if ((this._first_char != value))
				{
					this.Onfirst_charChanging(value);
					this.SendPropertyChanging();
					this._first_char = value;
					this.SendPropertyChanged("first_char");
					this.Onfirst_charChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="Int")]
		public System.Nullable<int> phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(22)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(64)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otherone", DbType="NVarChar(255)")]
		public string otherone
		{
			get
			{
				return this._otherone;
			}
			set
			{
				if ((this._otherone != value))
				{
					this.OnotheroneChanging(value);
					this.SendPropertyChanging();
					this._otherone = value;
					this.SendPropertyChanged("otherone");
					this.OnotheroneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_othertwo", DbType="NVarChar(255)")]
		public string othertwo
		{
			get
			{
				return this._othertwo;
			}
			set
			{
				if ((this._othertwo != value))
				{
					this.OnothertwoChanging(value);
					this.SendPropertyChanging();
					this._othertwo = value;
					this.SendPropertyChanged("othertwo");
					this.OnothertwoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_branch_tb_faculty", Storage="_tb_faculty", ThisKey="id", OtherKey="bid")]
		public EntitySet<tb_faculty> tb_faculty
		{
			get
			{
				return this._tb_faculty;
			}
			set
			{
				this._tb_faculty.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_faculty(tb_faculty entity)
		{
			this.SendPropertyChanging();
			entity.tb_branch = this;
		}
		
		private void detach_tb_faculty(tb_faculty entity)
		{
			this.SendPropertyChanging();
			entity.tb_branch = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_content")]
	public partial class tb_content : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _category_id;
		
		private string _title;
		
		private string _url;
		
		private string _pic;
		
		private string _status;
		
		private System.Nullable<int> _sort_order;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void Oncategory_idChanging(long value);
    partial void Oncategory_idChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    partial void OnpicChanging(string value);
    partial void OnpicChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void Onsort_orderChanging(System.Nullable<int> value);
    partial void Onsort_orderChanged();
    #endregion
		
		public tb_content()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", DbType="BigInt NOT NULL")]
		public long category_id
		{
			get
			{
				return this._category_id;
			}
			set
			{
				if ((this._category_id != value))
				{
					this.Oncategory_idChanging(value);
					this.SendPropertyChanging();
					this._category_id = value;
					this.SendPropertyChanged("category_id");
					this.Oncategory_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(200)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="NVarChar(500)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pic", DbType="NVarChar(300)")]
		public string pic
		{
			get
			{
				return this._pic;
			}
			set
			{
				if ((this._pic != value))
				{
					this.OnpicChanging(value);
					this.SendPropertyChanging();
					this._pic = value;
					this.SendPropertyChanged("pic");
					this.OnpicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(1)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sort_order", DbType="Int")]
		public System.Nullable<int> sort_order
		{
			get
			{
				return this._sort_order;
			}
			set
			{
				if ((this._sort_order != value))
				{
					this.Onsort_orderChanging(value);
					this.SendPropertyChanging();
					this._sort_order = value;
					this.SendPropertyChanged("sort_order");
					this.Onsort_orderChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_content_category")]
	public partial class tb_content_category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _name;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public tb_content_category()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_course")]
	public partial class tb_course : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _name;
		
		private System.Nullable<int> _credit;
		
		private System.Nullable<long> _tid;
		
		private string _tname;
		
		private string _otherone;
		
		private EntitySet<tb_sc> _tb_sc;
		
		private EntityRef<tb_teacher> _tb_teacher;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OncreditChanging(System.Nullable<int> value);
    partial void OncreditChanged();
    partial void OntidChanging(System.Nullable<long> value);
    partial void OntidChanged();
    partial void OntnameChanging(string value);
    partial void OntnameChanged();
    partial void OnotheroneChanging(string value);
    partial void OnotheroneChanged();
    #endregion
		
		public tb_course()
		{
			this._tb_sc = new EntitySet<tb_sc>(new Action<tb_sc>(this.attach_tb_sc), new Action<tb_sc>(this.detach_tb_sc));
			this._tb_teacher = default(EntityRef<tb_teacher>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(25)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_credit", DbType="Int")]
		public System.Nullable<int> credit
		{
			get
			{
				return this._credit;
			}
			set
			{
				if ((this._credit != value))
				{
					this.OncreditChanging(value);
					this.SendPropertyChanging();
					this._credit = value;
					this.SendPropertyChanged("credit");
					this.OncreditChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tid", DbType="BigInt")]
		public System.Nullable<long> tid
		{
			get
			{
				return this._tid;
			}
			set
			{
				if ((this._tid != value))
				{
					if (this._tb_teacher.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntidChanging(value);
					this.SendPropertyChanging();
					this._tid = value;
					this.SendPropertyChanged("tid");
					this.OntidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tname", DbType="NVarChar(255)")]
		public string tname
		{
			get
			{
				return this._tname;
			}
			set
			{
				if ((this._tname != value))
				{
					this.OntnameChanging(value);
					this.SendPropertyChanging();
					this._tname = value;
					this.SendPropertyChanged("tname");
					this.OntnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otherone", DbType="NVarChar(255)")]
		public string otherone
		{
			get
			{
				return this._otherone;
			}
			set
			{
				if ((this._otherone != value))
				{
					this.OnotheroneChanging(value);
					this.SendPropertyChanging();
					this._otherone = value;
					this.SendPropertyChanged("otherone");
					this.OnotheroneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_course_tb_sc", Storage="_tb_sc", ThisKey="id", OtherKey="cid")]
		public EntitySet<tb_sc> tb_sc
		{
			get
			{
				return this._tb_sc;
			}
			set
			{
				this._tb_sc.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_teacher_tb_course", Storage="_tb_teacher", ThisKey="tid", OtherKey="id", IsForeignKey=true)]
		public tb_teacher tb_teacher
		{
			get
			{
				return this._tb_teacher.Entity;
			}
			set
			{
				tb_teacher previousValue = this._tb_teacher.Entity;
				if (((previousValue != value) 
							|| (this._tb_teacher.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_teacher.Entity = null;
						previousValue.tb_course.Remove(this);
					}
					this._tb_teacher.Entity = value;
					if ((value != null))
					{
						value.tb_course.Add(this);
						this._tid = value.id;
					}
					else
					{
						this._tid = default(Nullable<long>);
					}
					this.SendPropertyChanged("tb_teacher");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_sc(tb_sc entity)
		{
			this.SendPropertyChanging();
			entity.tb_course = this;
		}
		
		private void detach_tb_sc(tb_sc entity)
		{
			this.SendPropertyChanging();
			entity.tb_course = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_datatime")]
	public partial class tb_datatime : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _data_time;
		
		private string _data_onup;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void Ondata_timeChanging(string value);
    partial void Ondata_timeChanged();
    partial void Ondata_onupChanging(string value);
    partial void Ondata_onupChanged();
    #endregion
		
		public tb_datatime()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_time", DbType="NVarChar(50)")]
		public string data_time
		{
			get
			{
				return this._data_time;
			}
			set
			{
				if ((this._data_time != value))
				{
					this.Ondata_timeChanging(value);
					this.SendPropertyChanging();
					this._data_time = value;
					this.SendPropertyChanged("data_time");
					this.Ondata_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_onup", DbType="NVarChar(50)")]
		public string data_onup
		{
			get
			{
				return this._data_onup;
			}
			set
			{
				if ((this._data_onup != value))
				{
					this.Ondata_onupChanging(value);
					this.SendPropertyChanging();
					this._data_onup = value;
					this.SendPropertyChanged("data_onup");
					this.Ondata_onupChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_faculty")]
	public partial class tb_faculty : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _name;
		
		private string _first_char;
		
		private System.Nullable<int> _phone;
		
		private string _introduce;
		
		private string _email;
		
		private System.Nullable<long> _bid;
		
		private string _bid_spec;
		
		private string _otherone;
		
		private EntityRef<tb_branch> _tb_branch;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onfirst_charChanging(string value);
    partial void Onfirst_charChanged();
    partial void OnphoneChanging(System.Nullable<int> value);
    partial void OnphoneChanged();
    partial void OnintroduceChanging(string value);
    partial void OnintroduceChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnbidChanging(System.Nullable<long> value);
    partial void OnbidChanged();
    partial void Onbid_specChanging(string value);
    partial void Onbid_specChanged();
    partial void OnotheroneChanging(string value);
    partial void OnotheroneChanged();
    #endregion
		
		public tb_faculty()
		{
			this._tb_branch = default(EntityRef<tb_branch>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(255)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_char", DbType="NVarChar(1)")]
		public string first_char
		{
			get
			{
				return this._first_char;
			}
			set
			{
				if ((this._first_char != value))
				{
					this.Onfirst_charChanging(value);
					this.SendPropertyChanging();
					this._first_char = value;
					this.SendPropertyChanged("first_char");
					this.Onfirst_charChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="Int")]
		public System.Nullable<int> phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_introduce", DbType="NVarChar(3000)")]
		public string introduce
		{
			get
			{
				return this._introduce;
			}
			set
			{
				if ((this._introduce != value))
				{
					this.OnintroduceChanging(value);
					this.SendPropertyChanging();
					this._introduce = value;
					this.SendPropertyChanged("introduce");
					this.OnintroduceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(22)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bid", DbType="BigInt")]
		public System.Nullable<long> bid
		{
			get
			{
				return this._bid;
			}
			set
			{
				if ((this._bid != value))
				{
					if (this._tb_branch.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnbidChanging(value);
					this.SendPropertyChanging();
					this._bid = value;
					this.SendPropertyChanged("bid");
					this.OnbidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bid_spec", DbType="NVarChar(50)")]
		public string bid_spec
		{
			get
			{
				return this._bid_spec;
			}
			set
			{
				if ((this._bid_spec != value))
				{
					this.Onbid_specChanging(value);
					this.SendPropertyChanging();
					this._bid_spec = value;
					this.SendPropertyChanged("bid_spec");
					this.Onbid_specChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otherone", DbType="NVarChar(300)")]
		public string otherone
		{
			get
			{
				return this._otherone;
			}
			set
			{
				if ((this._otherone != value))
				{
					this.OnotheroneChanging(value);
					this.SendPropertyChanging();
					this._otherone = value;
					this.SendPropertyChanged("otherone");
					this.OnotheroneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_branch_tb_faculty", Storage="_tb_branch", ThisKey="bid", OtherKey="id", IsForeignKey=true)]
		public tb_branch tb_branch
		{
			get
			{
				return this._tb_branch.Entity;
			}
			set
			{
				tb_branch previousValue = this._tb_branch.Entity;
				if (((previousValue != value) 
							|| (this._tb_branch.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_branch.Entity = null;
						previousValue.tb_faculty.Remove(this);
					}
					this._tb_branch.Entity = value;
					if ((value != null))
					{
						value.tb_faculty.Add(this);
						this._bid = value.id;
					}
					else
					{
						this._bid = default(Nullable<long>);
					}
					this.SendPropertyChanged("tb_branch");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_sc")]
	public partial class tb_sc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private System.Nullable<long> _cid;
		
		private System.Nullable<long> _sid;
		
		private string _grade;
		
		private string _s_spec;
		
		private string _c_spec;
		
		private EntityRef<tb_course> _tb_course;
		
		private EntityRef<tb_student> _tb_student;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OncidChanging(System.Nullable<long> value);
    partial void OncidChanged();
    partial void OnsidChanging(System.Nullable<long> value);
    partial void OnsidChanged();
    partial void OngradeChanging(string value);
    partial void OngradeChanged();
    partial void Ons_specChanging(string value);
    partial void Ons_specChanged();
    partial void Onc_specChanging(string value);
    partial void Onc_specChanged();
    #endregion
		
		public tb_sc()
		{
			this._tb_course = default(EntityRef<tb_course>);
			this._tb_student = default(EntityRef<tb_student>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cid", DbType="BigInt")]
		public System.Nullable<long> cid
		{
			get
			{
				return this._cid;
			}
			set
			{
				if ((this._cid != value))
				{
					if (this._tb_course.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncidChanging(value);
					this.SendPropertyChanging();
					this._cid = value;
					this.SendPropertyChanged("cid");
					this.OncidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sid", DbType="BigInt")]
		public System.Nullable<long> sid
		{
			get
			{
				return this._sid;
			}
			set
			{
				if ((this._sid != value))
				{
					if (this._tb_student.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsidChanging(value);
					this.SendPropertyChanging();
					this._sid = value;
					this.SendPropertyChanged("sid");
					this.OnsidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grade", DbType="NVarChar(100)")]
		public string grade
		{
			get
			{
				return this._grade;
			}
			set
			{
				if ((this._grade != value))
				{
					this.OngradeChanging(value);
					this.SendPropertyChanging();
					this._grade = value;
					this.SendPropertyChanged("grade");
					this.OngradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_spec", DbType="NVarChar(100)")]
		public string s_spec
		{
			get
			{
				return this._s_spec;
			}
			set
			{
				if ((this._s_spec != value))
				{
					this.Ons_specChanging(value);
					this.SendPropertyChanging();
					this._s_spec = value;
					this.SendPropertyChanged("s_spec");
					this.Ons_specChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_spec", DbType="NVarChar(100)")]
		public string c_spec
		{
			get
			{
				return this._c_spec;
			}
			set
			{
				if ((this._c_spec != value))
				{
					this.Onc_specChanging(value);
					this.SendPropertyChanging();
					this._c_spec = value;
					this.SendPropertyChanged("c_spec");
					this.Onc_specChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_course_tb_sc", Storage="_tb_course", ThisKey="cid", OtherKey="id", IsForeignKey=true)]
		public tb_course tb_course
		{
			get
			{
				return this._tb_course.Entity;
			}
			set
			{
				tb_course previousValue = this._tb_course.Entity;
				if (((previousValue != value) 
							|| (this._tb_course.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_course.Entity = null;
						previousValue.tb_sc.Remove(this);
					}
					this._tb_course.Entity = value;
					if ((value != null))
					{
						value.tb_sc.Add(this);
						this._cid = value.id;
					}
					else
					{
						this._cid = default(Nullable<long>);
					}
					this.SendPropertyChanged("tb_course");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_student_tb_sc", Storage="_tb_student", ThisKey="sid", OtherKey="id", IsForeignKey=true)]
		public tb_student tb_student
		{
			get
			{
				return this._tb_student.Entity;
			}
			set
			{
				tb_student previousValue = this._tb_student.Entity;
				if (((previousValue != value) 
							|| (this._tb_student.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_student.Entity = null;
						previousValue.tb_sc.Remove(this);
					}
					this._tb_student.Entity = value;
					if ((value != null))
					{
						value.tb_sc.Add(this);
						this._sid = value.id;
					}
					else
					{
						this._sid = default(Nullable<long>);
					}
					this.SendPropertyChanged("tb_student");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_student")]
	public partial class tb_student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _name;
		
		private string _id_card;
		
		private string _nplace;
		
		private string _sex;
		
		private string _phone;
		
		private string _education;
		
		private string _stu_class;
		
		private System.Nullable<long> _bid;
		
		private string _image;
		
		private string _bname;
		
		private string _othertwo;
		
		private string _password;
		
		private EntitySet<tb_sc> _tb_sc;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onid_cardChanging(string value);
    partial void Onid_cardChanged();
    partial void OnnplaceChanging(string value);
    partial void OnnplaceChanged();
    partial void OnsexChanging(string value);
    partial void OnsexChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OneducationChanging(string value);
    partial void OneducationChanged();
    partial void Onstu_classChanging(string value);
    partial void Onstu_classChanged();
    partial void OnbidChanging(System.Nullable<long> value);
    partial void OnbidChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OnbnameChanging(string value);
    partial void OnbnameChanged();
    partial void OnothertwoChanging(string value);
    partial void OnothertwoChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public tb_student()
		{
			this._tb_sc = new EntitySet<tb_sc>(new Action<tb_sc>(this.attach_tb_sc), new Action<tb_sc>(this.detach_tb_sc));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(25)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_card", DbType="NVarChar(50)")]
		public string id_card
		{
			get
			{
				return this._id_card;
			}
			set
			{
				if ((this._id_card != value))
				{
					this.Onid_cardChanging(value);
					this.SendPropertyChanging();
					this._id_card = value;
					this.SendPropertyChanged("id_card");
					this.Onid_cardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nplace", DbType="NVarChar(20)")]
		public string nplace
		{
			get
			{
				return this._nplace;
			}
			set
			{
				if ((this._nplace != value))
				{
					this.OnnplaceChanging(value);
					this.SendPropertyChanging();
					this._nplace = value;
					this.SendPropertyChanged("nplace");
					this.OnnplaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="NVarChar(2)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this.OnsexChanging(value);
					this.SendPropertyChanging();
					this._sex = value;
					this.SendPropertyChanged("sex");
					this.OnsexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(20)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_education", DbType="NVarChar(20)")]
		public string education
		{
			get
			{
				return this._education;
			}
			set
			{
				if ((this._education != value))
				{
					this.OneducationChanging(value);
					this.SendPropertyChanging();
					this._education = value;
					this.SendPropertyChanged("education");
					this.OneducationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stu_class", DbType="NVarChar(255)")]
		public string stu_class
		{
			get
			{
				return this._stu_class;
			}
			set
			{
				if ((this._stu_class != value))
				{
					this.Onstu_classChanging(value);
					this.SendPropertyChanging();
					this._stu_class = value;
					this.SendPropertyChanged("stu_class");
					this.Onstu_classChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bid", DbType="BigInt")]
		public System.Nullable<long> bid
		{
			get
			{
				return this._bid;
			}
			set
			{
				if ((this._bid != value))
				{
					this.OnbidChanging(value);
					this.SendPropertyChanging();
					this._bid = value;
					this.SendPropertyChanged("bid");
					this.OnbidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(255)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bname", DbType="NVarChar(255)")]
		public string bname
		{
			get
			{
				return this._bname;
			}
			set
			{
				if ((this._bname != value))
				{
					this.OnbnameChanging(value);
					this.SendPropertyChanging();
					this._bname = value;
					this.SendPropertyChanged("bname");
					this.OnbnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_othertwo", DbType="NVarChar(255)")]
		public string othertwo
		{
			get
			{
				return this._othertwo;
			}
			set
			{
				if ((this._othertwo != value))
				{
					this.OnothertwoChanging(value);
					this.SendPropertyChanging();
					this._othertwo = value;
					this.SendPropertyChanged("othertwo");
					this.OnothertwoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(64)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_student_tb_sc", Storage="_tb_sc", ThisKey="id", OtherKey="sid")]
		public EntitySet<tb_sc> tb_sc
		{
			get
			{
				return this._tb_sc;
			}
			set
			{
				this._tb_sc.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_sc(tb_sc entity)
		{
			this.SendPropertyChanging();
			entity.tb_student = this;
		}
		
		private void detach_tb_sc(tb_sc entity)
		{
			this.SendPropertyChanging();
			entity.tb_student = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_teacher")]
	public partial class tb_teacher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _name;
		
		private string _nplace;
		
		private string _sex;
		
		private string _phone;
		
		private string _education;
		
		private string _id_card;
		
		private string _position;
		
		private string _image;
		
		private string _bid;
		
		private string _password;
		
		private string _bname;
		
		private string _otherone;
		
		private string _othertwo;
		
		private string _otherthree;
		
		private EntitySet<tb_course> _tb_course;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnnplaceChanging(string value);
    partial void OnnplaceChanged();
    partial void OnsexChanging(string value);
    partial void OnsexChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OneducationChanging(string value);
    partial void OneducationChanged();
    partial void Onid_cardChanging(string value);
    partial void Onid_cardChanged();
    partial void OnpositionChanging(string value);
    partial void OnpositionChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OnbidChanging(string value);
    partial void OnbidChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnbnameChanging(string value);
    partial void OnbnameChanged();
    partial void OnotheroneChanging(string value);
    partial void OnotheroneChanged();
    partial void OnothertwoChanging(string value);
    partial void OnothertwoChanged();
    partial void OnotherthreeChanging(string value);
    partial void OnotherthreeChanged();
    #endregion
		
		public tb_teacher()
		{
			this._tb_course = new EntitySet<tb_course>(new Action<tb_course>(this.attach_tb_course), new Action<tb_course>(this.detach_tb_course));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(255)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nplace", DbType="NVarChar(255)")]
		public string nplace
		{
			get
			{
				return this._nplace;
			}
			set
			{
				if ((this._nplace != value))
				{
					this.OnnplaceChanging(value);
					this.SendPropertyChanging();
					this._nplace = value;
					this.SendPropertyChanged("nplace");
					this.OnnplaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="NVarChar(2)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this.OnsexChanging(value);
					this.SendPropertyChanging();
					this._sex = value;
					this.SendPropertyChanged("sex");
					this.OnsexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(20)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_education", DbType="NVarChar(20)")]
		public string education
		{
			get
			{
				return this._education;
			}
			set
			{
				if ((this._education != value))
				{
					this.OneducationChanging(value);
					this.SendPropertyChanging();
					this._education = value;
					this.SendPropertyChanged("education");
					this.OneducationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_card", DbType="NVarChar(50)")]
		public string id_card
		{
			get
			{
				return this._id_card;
			}
			set
			{
				if ((this._id_card != value))
				{
					this.Onid_cardChanging(value);
					this.SendPropertyChanging();
					this._id_card = value;
					this.SendPropertyChanged("id_card");
					this.Onid_cardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="NVarChar(10)")]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this.OnpositionChanging(value);
					this.SendPropertyChanging();
					this._position = value;
					this.SendPropertyChanged("position");
					this.OnpositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(255)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bid", DbType="NVarChar(255)")]
		public string bid
		{
			get
			{
				return this._bid;
			}
			set
			{
				if ((this._bid != value))
				{
					this.OnbidChanging(value);
					this.SendPropertyChanging();
					this._bid = value;
					this.SendPropertyChanged("bid");
					this.OnbidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(64)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bname", DbType="NVarChar(300)")]
		public string bname
		{
			get
			{
				return this._bname;
			}
			set
			{
				if ((this._bname != value))
				{
					this.OnbnameChanging(value);
					this.SendPropertyChanging();
					this._bname = value;
					this.SendPropertyChanged("bname");
					this.OnbnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otherone", DbType="NVarChar(300)")]
		public string otherone
		{
			get
			{
				return this._otherone;
			}
			set
			{
				if ((this._otherone != value))
				{
					this.OnotheroneChanging(value);
					this.SendPropertyChanging();
					this._otherone = value;
					this.SendPropertyChanged("otherone");
					this.OnotheroneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_othertwo", DbType="NVarChar(100)")]
		public string othertwo
		{
			get
			{
				return this._othertwo;
			}
			set
			{
				if ((this._othertwo != value))
				{
					this.OnothertwoChanging(value);
					this.SendPropertyChanging();
					this._othertwo = value;
					this.SendPropertyChanged("othertwo");
					this.OnothertwoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otherthree", DbType="NVarChar(100)")]
		public string otherthree
		{
			get
			{
				return this._otherthree;
			}
			set
			{
				if ((this._otherthree != value))
				{
					this.OnotherthreeChanging(value);
					this.SendPropertyChanging();
					this._otherthree = value;
					this.SendPropertyChanged("otherthree");
					this.OnotherthreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_teacher_tb_course", Storage="_tb_course", ThisKey="id", OtherKey="tid")]
		public EntitySet<tb_course> tb_course
		{
			get
			{
				return this._tb_course;
			}
			set
			{
				this._tb_course.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_course(tb_course entity)
		{
			this.SendPropertyChanging();
			entity.tb_teacher = this;
		}
		
		private void detach_tb_course(tb_course entity)
		{
			this.SendPropertyChanging();
			entity.tb_teacher = null;
		}
	}
}
#pragma warning restore 1591
